import { StyleSheet } from 'react-native';

export const baseModalStyles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    content: {
        width: '100%',
        maxWidth: 380,
        backgroundColor: '#0A0F1A',
        borderRadius: 28,
        borderWidth: 1,
        borderColor: 'rgba(0, 224, 255, 0.25)',
        padding: 24,
        shadowColor: '#00E0FF',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 12,
        overflow: 'hidden',
    },
    header: {
        alignItems: 'center',
        marginBottom: 20,
        gap: 12,
    },
    title: {
        color: '#FFF',
        fontSize: 24,
        fontWeight: '900',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    message: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 16,
        lineHeight: 24,
        textAlign: 'center',
        marginBottom: 24,
    },
    footer: {
        flexDirection: 'row',
        gap: 12,
    },
    primaryBtn: {
        flex: 1,
        height: 56,
        backgroundColor: '#00E0FF',
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#00E0FF',
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 6,
    },
    primaryBtnText: {
        color: '#000',
        fontSize: 15,
        fontWeight: '900',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    secondaryBtn: {
        flex: 1,
        height: 56,
        backgroundColor: 'rgba(255, 255, 255, 0.04)',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    secondaryBtnText: {
        color: 'rgba(255, 255, 255, 0.5)',
        fontSize: 14,
        fontWeight: '800',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    closeButton: {
        position: 'absolute',
        top: 16,
        right: 16,
        padding: 4,
    }
});
