import { StyleSheet, Dimensions } from 'react-native';

export const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

export const GRID_COLS = 9;

export const BUBBLE_SIZE = Math.floor(SCREEN_WIDTH / 10);
export const ROW_HEIGHT = BUBBLE_SIZE * 0.86;
export const CANNON_SIZE = 80;
export const FOOTER_BOTTOM = 200; // Moved down closer to HUD as requested
export const GRID_TOP = 10;

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#000" },

    // Command Deck Styles
    hudTopContainer: {
        position: 'absolute',
        top: 50,
        width: '100%',
        alignItems: 'center',
        zIndex: 60,
    },
    topCard: {
        flexDirection: 'row',
        width: '90%',
        height: 60,
        backgroundColor: 'rgba(20, 20, 30, 0.9)',
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#00E0FF', // Neon Cyan
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        shadowColor: '#00E0FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 10,
        elevation: 20,
    },
    verticalDivider: {
        width: 1,
        height: 25,
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    starContainer: {
        flexDirection: 'row',
        gap: 2,
    },
    starIcon: {
        fontSize: 16,
    },
    topExitBtn: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: 'rgba(239, 68, 68, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(239, 68, 68, 0.5)',
    },

    hudBottomContainer: {
        position: 'absolute',
        bottom: 30, // Reduced from 40 for more compact layout
        left: 0,
        right: 0,
        alignItems: 'center',
        zIndex: 50,
    },
    uCard: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        backgroundColor: 'rgba(20, 20, 30, 0.92)',
        paddingHorizontal: 25, // Increased for wider look
        paddingTop: 10,
        paddingBottom: 12,
        borderRadius: 30,
        borderWidth: 2,
        borderColor: '#00E0FF',
        gap: 20, // Increased gap for wider distribution
        shadowColor: '#00E0FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
        elevation: 20,
    },
    uWingLeft: {
        flexDirection: 'row',
        gap: 10,
        paddingBottom: 5,
    },
    uWingRight: {
        flexDirection: 'row',
        gap: 10,
        paddingBottom: 5,
    },
    uCenterAmmo: {
        marginBottom: 6, // Reduced from 10
    },
    ammoRing: {
        width: 50, // Reduced from 60
        height: 50, // Reduced from 60
        borderRadius: 25,
        backgroundColor: 'rgba(0, 224, 255, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#00E0FF',
        shadowColor: '#00E0FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 10,
        elevation: 10,
    },
    ammoBubble: {
        width: 36, // Reduced from 44
        height: 36, // Reduced from 44
        borderRadius: 18,
        borderWidth: 2,
        borderColor: '#fff',
        shadowColor: '#fff',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
        elevation: 8,
    },

    statValue: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '800',
        fontFamily: 'monospace',
    },
    instructionTab: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        gap: 2,
        paddingHorizontal: 8,
    },
    helpIcon: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: 'rgba(74, 144, 226, 0.2)',
        borderWidth: 1.5,
        borderColor: '#4A90E2',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#4A90E2',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
        elevation: 5,
    },
    helpIconText: {
        color: '#4A90E2',
        fontSize: 14,
        fontWeight: '800',
        fontStyle: 'italic',
        textAlign: 'center',
        lineHeight: 16,
    },
    instructionLabel: {
        color: '#4A90E2',
        fontSize: 9,
        fontWeight: '700',
        letterSpacing: 1,
    },
    iconText: {
        fontSize: 18,
        color: '#fff',
    },
    abilityBtn: {
        width: 38, // Reduced from 42
        height: 38, // Reduced from 42
        borderRadius: 12, // Reduced from 14
        backgroundColor: 'rgba(0, 224, 255, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: '#00E0FF',
    },
    abilityBtnActive: {
        backgroundColor: 'rgba(255, 214, 10, 0.3)',
        borderColor: '#FFD60A',
    },
    abilityText: {
        fontSize: 18, // Reduced from 20
    },

    borderContainer: {
        position: 'absolute',
        left: 10,
        right: 10,
        zIndex: 1,
    },
    borderBox: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 20,
        borderWidth: 2,
        borderStyle: 'dashed',
    },

    gameArea: { flex: 1 },
    bg: { ...StyleSheet.absoluteFillObject, opacity: 0.8, resizeMode: 'cover' },
    bubble: {
        position: "absolute",
        width: BUBBLE_SIZE,
        height: BUBBLE_SIZE,
        borderRadius: BUBBLE_SIZE / 2,
        borderWidth: 1.5,
        borderColor: "rgba(255,255,255,0.4)",
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.4,
        shadowRadius: 4,
        elevation: 5
    },
    bubbleInner: {
        position: 'absolute',
        width: '100%',
        height: '100%',
        borderRadius: BUBBLE_SIZE / 2,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.15)',
        backgroundColor: 'transparent',
        overflow: 'hidden',
    },
    planetBands: {
        position: 'absolute',
        width: '150%',
        height: '100%',
        top: 0,
        left: '-25%',
        borderTopWidth: 6,
        borderBottomWidth: 4,
        borderColor: 'rgba(0,0,0,0.15)',
        opacity: 0.6,
    },
    planetCrater1: {
        position: 'absolute',
        width: '20%',
        height: '20%',
        borderRadius: 10,
        backgroundColor: 'rgba(0,0,0,0.12)',
        top: '20%',
        right: '25%',
    },
    planetCrater2: {
        position: 'absolute',
        width: '12%',
        height: '12%',
        borderRadius: 6,
        backgroundColor: 'rgba(0,0,0,0.1)',
        bottom: '25%',
        left: '30%',
    },
    planetCrater3: {
        position: 'absolute',
        width: '15%',
        height: '15%',
        borderRadius: 8,
        backgroundColor: 'rgba(0,0,0,0.08)',
        bottom: '40%',
        right: '35%',
    },
    planetRing: {
        position: 'absolute',
        width: '140%',
        height: '35%',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.25)',
        top: '35%',
        left: '-20%',
        transform: [{ rotate: '-15deg' }],
        zIndex: -1,
    },
    bubbleHighlight: {
        position: 'absolute',
        top: '5%',
        left: '10%',
        width: '40%',
        height: '40%',
        borderRadius: BUBBLE_SIZE / 4,
        backgroundColor: 'rgba(255,255,255,0.4)',
        transform: [{ rotate: '-10deg' }],
        zIndex: 2,
    },
    bubbleGloss: {
        position: 'absolute',
        bottom: '10%',
        right: '10%',
        width: '30%',
        height: '15%',
        borderRadius: BUBBLE_SIZE,
        backgroundColor: 'rgba(255,255,255,0.2)',
        transform: [{ rotate: '45deg' }],
        zIndex: 2,
    },
    bubbleIconContainer: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    ghostBubble: {
        opacity: 0.6,
        borderStyle: 'dashed',
        backgroundColor: 'transparent',
        borderColor: '#fff',
    },
    simpleBubble: {
        position: "absolute",
        width: BUBBLE_SIZE,
        height: BUBBLE_SIZE,
        borderRadius: BUBBLE_SIZE / 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    shine: { position: "absolute", top: "15%", left: "15%", width: "25%", height: "25%", backgroundColor: "rgba(255,255,255,0.4)", borderRadius: 10 },
    laserDot: {
        position: "absolute",
        width: 12,
        height: 3,
        borderRadius: 1.5,
        zIndex: 100,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.9,
        shadowRadius: 4,
        elevation: 8,
    },
    dot: {
        position: "absolute",
        width: 6,
        height: 6,
        borderRadius: 3,
        zIndex: 100,
    },
    hintContainer: {
        position: 'absolute',
        bottom: 120, // Adjusted from 150 to match new layout
        width: SCREEN_WIDTH,
        alignItems: 'center',
    },
    hintText: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 12, // Reduced from 13
        fontWeight: 'bold',
        letterSpacing: 1.2,
        textShadowColor: 'rgba(0,0,0,0.8)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    footer: { position: "absolute", bottom: FOOTER_BOTTOM, width: "100%", alignItems: "center" },
    cannon: {
        width: CANNON_SIZE,
        height: CANNON_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10
    },
    pulseRing: {
        position: 'absolute',
        width: CANNON_SIZE + 20,
        height: CANNON_SIZE + 20,
        borderRadius: (CANNON_SIZE + 20) / 2,
        borderWidth: 3,
        borderColor: '#fff',
        backgroundColor: 'transparent',
        zIndex: 5,
    },
    muzzleBlast: {
        position: 'absolute',
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 3,
        borderColor: '#00E0FF',
        backgroundColor: 'rgba(0, 224, 255, 0.2)',
        bottom: 50,
        zIndex: 15,
        shadowColor: '#00E0FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 15,
    },
    modalOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modalContent: {
        width: '92%',
        backgroundColor: 'rgba(5, 5, 10, 0.98)',
        borderTopLeftRadius: 40,
        borderBottomRightRadius: 40,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderWidth: 2,
        borderColor: '#00E0FF',
        paddingHorizontal: 12,
        paddingVertical: 20,
        shadowColor: '#00E0FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 25,
        elevation: 15,
        overflow: 'hidden',
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 28,
        fontWeight: '900',
        color: '#fff',
        marginBottom: 20,
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 28,
    },
    modalStars: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalScore: {
        fontSize: 20,
        color: '#fbbf24',
        fontWeight: 'bold',
        marginBottom: 30,
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 20,
        alignItems: 'center',
    },
    modalBtnPrimary: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: '#3b82f6',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#3b82f6',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
    },
    modalBtnSecondary: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'rgba(255,255,255,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    statItem: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        gap: 0,
    },
    statLabel: {
        color: '#aaa',
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 1,
    },

    metalGridOverlay: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
        borderRadius: BUBBLE_SIZE / 2,
        overflow: 'hidden',
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
    },
    metalOuterRing: {
        position: 'absolute',
        width: '95%',
        height: '95%',
        borderRadius: BUBBLE_SIZE / 2,
        borderWidth: 2,
        borderColor: 'rgba(139, 139, 139, 0.8)',
        backgroundColor: 'transparent',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
    },
    metalInnerRing: {
        position: 'absolute',
        width: '75%',
        height: '75%',
        borderRadius: BUBBLE_SIZE / 2,
        borderWidth: 1.5,
        borderColor: 'rgba(168, 168, 168, 0.7)',
        backgroundColor: 'transparent',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.4,
        shadowRadius: 2,
    },
    metalCrossContainer: {
        position: 'absolute',
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    metalCrossHorizontal: {
        position: 'absolute',
        width: '60%',
        height: 2,
        backgroundColor: 'rgba(144, 144, 144, 0.7)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.5,
        shadowRadius: 1,
    },
    metalCrossVertical: {
        position: 'absolute',
        width: 2,
        height: '60%',
        backgroundColor: 'rgba(144, 144, 144, 0.7)',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 1,
    },
    metalDiagonal1: {
        position: 'absolute',
        width: '50%',
        height: 1.5,
        backgroundColor: 'rgba(122, 122, 122, 0.6)',
        transform: [{ rotate: '45deg' }],
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 1,
    },
    metalDiagonal2: {
        position: 'absolute',
        width: '50%',
        height: 1.5,
        backgroundColor: 'rgba(122, 122, 122, 0.6)',
        transform: [{ rotate: '-45deg' }],
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 1,
    },
    metalBolt: {
        position: 'absolute',
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: 'rgba(107, 107, 107, 0.8)',
        borderWidth: 0.5,
        borderColor: 'rgba(74, 74, 74, 0.8)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.6,
        shadowRadius: 1,
    },
    metallicShine: {
        position: 'absolute',
        top: '10%',
        left: '20%',
        width: '25%',
        height: '15%',
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 10,
        transform: [{ rotate: '-30deg' }],
        opacity: 0.5,
    },
    lightningEffect: {
        position: 'absolute',
        top: -5,
        right: -5,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: 'rgba(255, 214, 10, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#FFD60A',
        shadowColor: '#FFD60A',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        zIndex: 20,
    },
    bombEffect: {
        position: 'absolute',
        top: -5,
        left: -5,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: 'rgba(255, 149, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#FF9500',
        shadowColor: '#FF9500',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        zIndex: 20,
    },
    freezeEffect: {
        position: 'absolute',
        top: -5,
        left: -5,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: 'rgba(0, 224, 255, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#00E0FF',
        shadowColor: '#00E0FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        zIndex: 20,
    },
    fireEffect: {
        position: 'absolute',
        top: -5,
        right: -5,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: 'rgba(255, 59, 48, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#FF3B30',
        shadowColor: '#FF3B30',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        zIndex: 20,
    },
    iceOverlay: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(200, 255, 255, 0.3)',
        borderRadius: BUBBLE_SIZE / 2,
        borderWidth: 2,
        borderColor: '#00ffff',
        zIndex: 15,
    },
    iceGlaze: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '40%',
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
    },
    iceShine: {
        position: 'absolute',
        top: '10%',
        left: '10%',
        width: '30%',
        height: '30%',
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        borderRadius: 15,
    },
    iceCrystal1: {
        position: 'absolute',
        bottom: '20%',
        right: '20%',
        width: 8,
        height: 8,
        backgroundColor: '#fff',
        transform: [{ rotate: '45deg' }]
    },
    iceCrystal2: {
        position: 'absolute',
        top: '40%',
        left: '20%',
        width: 6,
        height: 6,
        backgroundColor: '#fff',
        transform: [{ rotate: '45deg' }]
    },
});
