import { StyleSheet, Dimensions } from 'react-native';

export const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    scrollView: {
        flex: 1,
    },
    roadmapContainer: {
        paddingVertical: 120,
        paddingHorizontal: 20,
    },
    loadingContainer: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2000,
    },
    loadingSpaceship: {
        width: 250,
        height: 250,
    },
    loadingText: {
        color: '#00E0FF',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'monospace',
        marginTop: -20,
        textAlign: 'center',
    },

    // DASHBOARD HEADER STYLES
    dashboardContainer: {
        position: 'absolute',
        top: 50,
        left: '4%',
        right: '4%',
        backgroundColor: 'rgba(5, 5, 10, 0.98)',
        borderTopLeftRadius: 40,
        borderBottomRightRadius: 40,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderWidth: 2,
        borderColor: '#00E0FF',
        zIndex: 100,
        paddingHorizontal: 12,
        paddingVertical: 14,
        shadowColor: '#00E0FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 25,
        elevation: 15,
        overflow: 'hidden',
    },
    dashboardTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingBottom: 15,
    },
    titleBlock: {
        flex: 1,
    },
    cardTitle: {
        fontSize: 24,
        fontWeight: '900',
        color: '#fff',
        letterSpacing: 2,
        lineHeight: 24,
    },
    cardSubtitle: {
        fontSize: 12,
        fontWeight: '600',
        color: '#00E0FF',
        letterSpacing: 4,
    },
    userEmail: {
        fontSize: 10,
        color: '#FFD60A',
        marginTop: 4,
        fontFamily: 'monospace',
    },
    dividerVertical: {
        width: 1.5,
        height: 40,
        backgroundColor: 'rgba(255,255,255,0.1)',
        marginHorizontal: 15,
    },
    statsBlock: {
        flexDirection: 'column',
        gap: 8,
    },
    statChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.08)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        minWidth: 80,
    },
    statNumber: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '700',
        marginLeft: 8,
        fontFamily: 'monospace',
    },
    dashboardDivider: {
        height: 1,
        backgroundColor: 'rgba(255,255,255,0.1)',
        width: '100%',
    },
    dashboardBottom: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 10,
        flexWrap: 'nowrap',
    },
    actionBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 4,
        borderRadius: 12,
        flexShrink: 1,
    },
    menuText: {
        fontSize: 10,
        fontWeight: '900',
        marginLeft: 4,
        letterSpacing: 0,
    },
    dividerVerticalSmall: {
        width: 1,
        height: 12,
        backgroundColor: 'rgba(255,255,255,0.15)',
        marginHorizontal: 1,
    },

    listContent: {
        paddingBottom: 200,
    },
    connectingDot: {
        position: 'absolute',
        width: 5,
        height: 5,
        borderRadius: 2.5,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        zIndex: 1,
    },
    levelItemContainer: {
        height: 220,
        width: 150,
        alignItems: 'center',
        justifyContent: 'center',
    },
    ufoTouchable: {
        width: 150,
        height: 180,
        alignItems: 'center',
        justifyContent: 'center',
    },
    nebulaGlow: {
        position: 'absolute',
        width: 200,
        height: 200,
        borderRadius: 100,
    },
    centeredLayers: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    wavePulse: {
        position: 'absolute',
    },
    nodeCore: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
    },
    activeNodeCore: {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        shadowOpacity: 1,
        shadowRadius: 30,
    },
    lockOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        borderRadius: 50,
    },
    titleContainer: {
        marginTop: 15,
        backgroundColor: 'rgba(0,0,0,0.5)',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    levelTitleText: {
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
    },
    orbitalRing: {
        position: 'absolute',
        borderWidth: 3,
        borderStyle: 'dashed',
        shadowColor: '#FFF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        opacity: 1,
    },
    ufoIcon: { width: 85, height: 85, opacity: 1 },
    levelTextContainer: {
        position: 'absolute',
        bottom: -30,
        alignSelf: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    levelNumberText: {
        fontSize: 16,
        fontWeight: '900',
        textShadowColor: '#000',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 4,
        letterSpacing: 1,
        textAlign: 'center',
    },
    starsContainer: {
        position: 'absolute',
        top: -45,
        flexDirection: 'row',
        backgroundColor: 'rgba(0,0,0,0.8)',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    starMini: { fontSize: 13, marginHorizontal: 1 },

    // Shop Modal Styles
    shopOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    shopModal: {
        width: '90%',
        maxHeight: '80%',
        backgroundColor: 'rgba(20, 20, 30, 0.95)',
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#00E0FF',
        padding: 20,
    },
    shopHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    shopTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
        letterSpacing: 1,
    },
    shopCloseBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 59, 48, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 59, 48, 0.5)',
    },
    shopCoins: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        padding: 10,
        backgroundColor: 'rgba(255, 215, 0, 0.1)',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: 'rgba(255, 215, 0, 0.3)',
    },
    shopCoinsText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#FFD700',
        marginLeft: 8,
    },
    shopGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    shopItem: {
        width: '48%',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderRadius: 15,
        padding: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        alignItems: 'center',
    },
    shopItemIcon: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    shopItemName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 5,
    },
    shopItemDesc: {
        fontSize: 12,
        color: '#aaa',
        textAlign: 'center',
        marginBottom: 15,
    },
    shopItemFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
    shopItemPrice: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    shopPriceText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFD700',
        marginLeft: 5,
    },
    shopBuyBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#00E0FF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    shopBuyBtnDisabled: {
        backgroundColor: 'rgba(142, 142, 147, 0.3)',
    },
    shopInventoryBadge: {
        position: 'absolute',
        top: 5,
        right: 5,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#00FF88',
        justifyContent: 'center',
        alignItems: 'center',
    },
    shopInventoryText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#fff',
    },
    staticSpaceship: {
        position: 'absolute',
        zIndex: 50,
        top: -45, // Float slightly higher and more centered
    },
    spaceshipLottie: {
        width: '100%',
        height: '100%',
    },
});
